"""Added Chiredzi and real users

Revision ID: abb3dbb5c31b
Revises: 
Create Date: 2026-01-31 22:49:11.679248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb3dbb5c31b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_payables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('creditors', sa.Float(), nullable=True),
    sa.Column('creditors_project', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_receivables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('paid', sa.Float(), nullable=True),
    sa.Column('due', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.Column('usd_balance', sa.Float(), nullable=True),
    sa.Column('zig_balance', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'bank_name', name='_bank_date_uc')
    )
    op.create_table('gas_plant_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('industrial_gases_cyl', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operational_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('u1_hours', sa.Integer(), nullable=True),
    sa.Column('u1_minutes', sa.Integer(), nullable=True),
    sa.Column('u2_hours', sa.Integer(), nullable=True),
    sa.Column('u2_minutes', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_main',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('unit_1_cumulative', sa.Float(), nullable=True),
    sa.Column('unit_2_cumulative', sa.Float(), nullable=True),
    sa.Column('rolling_non_tmt', sa.Float(), nullable=True),
    sa.Column('rolling_tmt', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_sponge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('produced_tns', sa.Float(), nullable=True),
    sa.Column('lost_tns', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('angles_sales', sa.Float(), nullable=True),
    sa.Column('flats_sales', sa.Float(), nullable=True),
    sa.Column('window_sections_sales', sa.Float(), nullable=True),
    sa.Column('fencing_standard_sales', sa.Float(), nullable=True),
    sa.Column('channel_iron_sales', sa.Float(), nullable=True),
    sa.Column('other_sections_sales', sa.Float(), nullable=True),
    sa.Column('redcliff_sales', sa.Float(), nullable=True),
    sa.Column('harare_sales', sa.Float(), nullable=True),
    sa.Column('mutare_sales', sa.Float(), nullable=True),
    sa.Column('bulawayo_sales', sa.Float(), nullable=True),
    sa.Column('chiredzi_sales', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrap_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('supplied_tns', sa.Float(), nullable=True),
    sa.Column('total_purchased_tns', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('scrap_data')
    op.drop_table('sales_data')
    op.drop_table('production_sponge')
    op.drop_table('production_main')
    op.drop_table('operational_data')
    op.drop_table('gas_plant_data')
    op.drop_table('daily_balance')
    op.drop_table('bank_interest')
    op.drop_table('account_receivables')
    op.drop_table('account_payables')
    # ### end Alembic commands ###
